# This is the production variant of
# docker deployment for smart-rack-backend
version: '3'
services:

  # staging instance
  app-staging:
    image: index.docker.io/wellnessappbackend/wellnessappbackend:staging
    container_name: 'app-staging'
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=staging
      - MONGO_HOST=database
      - MONGO_DB=wellnessapp-staging
      - HOST=http://ec2-18-222-206-211.us-east-2.compute.amazonaws.com/staging/api/
    env_file:
      - .env

  # app-admin:
  #   image: index.docker.io/wellnessappbackend/admin:master
  #   container_name: 'app-admin'
  #   ports:
  #     - 8001:8001
  #   environment:
  #     - NODE_ENV=staging
  #     - URL=http://ec2-18-222-206-211.us-east-2.compute.amazonaws.com/staging/api/


  # nginx for port forwarding and proxy server
  nginx:
    image: nginx:latest
    container_name: 'nginx'
    depends_on:
      - app-staging
    ports:
      - "80:80"
    volumes:
      - ./configurations/nginx-staging.conf:/etc/nginx/conf.d/default.conf
      # - ./certs:/etc/nginx/certs

  watchtower:
    image: v2tec/watchtower
    container_name: 'watchtower'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.docker/config.json:/config.json
    command: --interval 10 --cleanup
